### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by BHX2** [niclasko/Cypher.js#1]
I'm quite interested in your javascript cypher implementation. I haven't come across many that have implemented as much of the language, especially in JS. If you have a non-minified version that you'd be open to sharing, I would be interested in being able to read through it to see how it works. Thank you either way and appreciate the star.

**Comment by BHX2** [comment]
Saw the un-minified source file. Thank you!

**Comment by kapilpipaliya** [comment]
Hi Niclas,

Can I get the full source code of the project? I want to start a project based on your library.

Again, thank you so much for sharing the library.

Kind regards
